# Generated by Django 5.0.6 on 2024-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
    ]
