# Generated by Django 5.0.6 on 2024-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
