# Generated by Django 5.0.6 on 2025-06-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchexperience',
            name='professor',
            field=models.CharField(default='Dr. Leite', max_length=200),
            preserve_default=False,
        ),
    ]
