# Generated by Django 5.0.6 on 2026-08-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchexperience_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchexperience',
            name='professor',
        ),
    ]
