# Generated by Django 5.0.6 on 2026-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_remove_researchexperience_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchexperience',
            name='department',
            field=models.CharField(default='UF', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchexperience',
            name='professor',
            field=models.CharField(default='Dr.', max_length=200),
            preserve_default=False,
        ),
    ]
