# Generated by Django 5.0.6 on 2024-06-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_title', models.CharField(max_length=200)),
                ('uf_code', models.CharField(max_length=50)),
                ('high_school_title', models.CharField(blank=True, max_length=200, null=True)),
                ('high_school_code', models.CharField(blank=True, max_length=50, null=True)),
                ('term', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
