# Generated by Django 5.0.6 on 2024-06-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseentry_delete_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseEntry',
            new_name='Course',
        ),
    ]
